# Welcome to the first Numpy/Jupyter demo

In [1]:
import numpy # If no erros, then your environment got activated

## Let's build a simple calculator

In [2]:
a = input('Enter the first num: ')
b = input('Enter the second num: ')
def basic_calc(a, b):
    result = int(a) + int(b)
    return result

Enter the first num:  4
Enter the second num:  7


In [3]:
basic_calc(a,b)

11

In [4]:
assert basic_calc('5','6') == 11
assert basic_calc(-5,3) == -2
print("##### All tests passed ######")

##### All tests passed ######


## NUMPY DEMO

In [5]:
import numpy as np

In [8]:
list_of_nums = [5,2,7,4]

In [9]:
array_of_nums = np.array([5,2,7,4])

In [10]:
type(list_of_nums)

list

In [11]:
type(array_of_nums)

numpy.ndarray

## Generate data set

In [12]:
dataset = np.genfromtxt('./student_scores.csv', delimiter=',', skip_header=True)

In [13]:
dataset

array([[ 2.5, 21. ],
       [ 5.1, 47. ],
       [ 3.2, 27. ],
       [ 8.5, 75. ],
       [ 3.5, 30. ],
       [ 1.5, 20. ],
       [ 9.2, 88. ],
       [ 5.5, 60. ],
       [ 8.3, 81. ],
       [ 2.7, 25. ],
       [ 7.7, 85. ],
       [ 5.9, 62. ],
       [ 4.5, 41. ],
       [ 3.3, 42. ],
       [ 1.1, 17. ],
       [ 8.9, 95. ],
       [ 2.5, 30. ],
       [ 1.9, 24. ],
       [ 6.1, 67. ],
       [ 7.4, 69. ],
       [ 2.7, 30. ],
       [ 4.8, 54. ],
       [ 3.8, 35. ],
       [ 6.9, 76. ],
       [ 7.8, 86. ],
       [ 2.7, 60. ]])

In [14]:
type(dataset)

numpy.ndarray

In [15]:
dataset[0]

array([ 2.5, 21. ])

In [16]:
dataset[0][1]

21.0

In [17]:
dataset[0,1]

21.0

### Calculate average hours studied by the student

In [18]:
hours_studied = dataset[:,0]

In [19]:
hours_studied

array([2.5, 5.1, 3.2, 8.5, 3.5, 1.5, 9.2, 5.5, 8.3, 2.7, 7.7, 5.9, 4.5,
       3.3, 1.1, 8.9, 2.5, 1.9, 6.1, 7.4, 2.7, 4.8, 3.8, 6.9, 7.8, 2.7])

In [20]:
type(hours_studied)

numpy.ndarray

In [21]:
avg = np.average(hours_studied)

In [22]:
avg

4.923076923076923

In [23]:
avg = np.mean(hours_studied)

In [24]:
avg

4.923076923076923

In [26]:
median = np.median(hours_studied)

In [27]:
median

4.65

### Shape of dataset

In [31]:
dataset.shape

(26, 2)