# Hello

In [1]:
import numpy as np

In [4]:
matrix = np.arange(64)

In [5]:
matrix

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [9]:
mtrx = np.arange(64).reshape(16,4)
print(mtrx)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]
 [48 49 50 51]
 [52 53 54 55]
 [56 57 58 59]
 [60 61 62 63]]


In [10]:
print(mtrx[3,3])
print(mtrx[3][3])

15
15


In [11]:
mtrx[4,:]

array([16, 17, 18, 19])

In [12]:
mtrx[4, 1:4]

array([17, 18, 19])

In [35]:
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [17]:
len(arr)

16

In [19]:
15//2

7

In [20]:
x = 3
y = 7
print(f'x:{x}, y:{y}')
x,y = y,x
print(f'x:{x}, y:{y}')

x:3, y:7
x:7, y:3


In [40]:
def reverse_array(arr, copy=True):
  if copy:
    copied_arr = arr.copy()
  mid = len(copied_arr) // 2
  for i in range(mid):
    copied_arr[i],copied_arr[-i-1] = copied_arr[-i-1],copied_arr[i]
  return copied_arr

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [42]:
reversed = reverse_array(arr)

In [43]:
reversed

array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [76]:
new_arr = np.array([1,2,3,4])[:]

In [77]:
new_arr

array([1, 2, 3, 4])

In [78]:
newer = new_arr.copy()

In [79]:
newer

array([1, 2, 3, 4])

In [80]:
equal = newer == new_arr

In [81]:
equal

array([ True,  True,  True,  True])

In [82]:
type(equal)

numpy.ndarray

In [83]:
newer is new_arr

False

In [84]:
newer[0] = 99

In [85]:
newer

array([99,  2,  3,  4])

In [86]:
new_arr

array([1, 2, 3, 4])

In [91]:
def run_tests():

  # test 1
  some_arr = np.array([1,2,3,4])
  new_arr = some_arr[:]
  assert some_arr is not new_arr
  some_arr[0] = 999
  assert new_arr[0] != 1


  # test 2
  some = np.array([1,2,3,4])
  other = some.view()
  some[0] = 999
  assert other[0] == 999


  # test 3
  some = np.array([1,2,3,4])
  other = some.copy()
  some[0] = 999
  assert other[0] == 1
  
  print('........ SUCCESS .........')

In [92]:
run_tests()

........ SUCCESS .........


In [108]:
some = np.array([5,6,7,8])
other = np.array(some)
some[0] = 55
other

array([5, 6, 7, 8])

# Buy Low Sell High

In [112]:
prices = np.full(100, fill_value=9)

In [113]:
prices

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

In [114]:
np.zeros(50)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [115]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [116]:
np.full(20, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

# Memory allocation in Python

In [94]:
arr1 = [1,2,3,4,5]

In [95]:
arr2 = arr1

In [96]:
arr2

[1, 2, 3, 4, 5]

In [97]:
arr1 == arr2

True

In [98]:
arr1 is arr2

True

In [99]:
var1 = 8

In [100]:
var2 = var1

In [101]:
var1 == var2

True

In [102]:
var1 is var2

True

In [103]:
var1

8

In [104]:
var2

8

In [105]:
var1 = 9

In [106]:
var1

9

In [107]:
var2

8